config/routes.rb
Spree::Core::Engine.routes.draw do
  namespace :admin do
    namespace :marketing do
      resources :lists, only: %i[show index]
      resources :campaigns, only: %i[show index] do
        member do
          get :display_recipient_emails
        end
      end
      post 'campaigns/sync', to: 'campaigns#sync'
    end
  end
end

app/models/concerns/spree/marketing/acts_as_multi_list.rb
module Spree
  module Marketing
    module ActsAsMultiList
      extend ActiveSupport::Concern

      def display_name
        self.class::NAME_TEXT + ' (' + entity_name + ')'
      end

      def entity_name
        entity.name
      end

      class_methods do
        def generator
          lists = []
          # data returns polymorphic entity ids or searched keywords
          data.each do |entity|
            if list = load_list_by_entity(entity)
              list.update_list
            else
              # ENTITY_KEY constant defines the attribute we are updating(searched_keyword/entity_id)
              new(self::ENTITY_KEY.to_s => entity, entity_type: self::ENTITY_TYPE).generate
              list = load_list_by_entity(entity)
            end
            lists << list
          end
          delete_lists(lists) if lists.any?
        end

        def delete_lists(lists)
          ListCleanupJob.perform_later where.not(uid: lists.map(&:uid)).pluck(:uid)
        end

        private

        def load_list_by_entity(entity)
          find_by(self::ENTITY_KEY.to_s => entity)
        end
      end
    end
  end
end

app/models/concerns/spree/marketing/calculate_reports.rb
module Spree
  module Marketing
    module CalculateReports
      REPORT_TITLE_KEYS = Spree::Marketing::List::AVAILABLE_REPORTS.collect { |key| key.to_s.remove('_by') }

      def log_ins_by
        actor_ids = Spree::PageEvent.of_registered_users
                                    .where(actor_id: user_ids, actor_type: Spree.user_class.to_s)
                                    .where('created_at >= :scheduled_time', scheduled_time: scheduled_at)
                                    .distinct
                                    .pluck(:actor_id)

        Spree.user_class.where(id: actor_ids).pluck(:email)
      end

      def purchases_by
        Spree::Order.of_registered_users
                    .where('completed_at >= :scheduled_time', scheduled_time: scheduled_at)
                    .where(email: contacts.pluck(:email))
                    .distinct
                    .pluck(:email)
      end

      def cart_additions_by
        actor_ids = Spree::CartEvent.where('created_at >= :scheduled_time', scheduled_time: scheduled_at)
                                    .where(activity: 'add')
                                    .distinct
                                    .pluck(:actor_id)

        Spree::Order.of_registered_users
                    .where(id: actor_ids, user_id: user_ids)
                    .distinct
                    .pluck(:email)
      end

      def product_views_by
        actor_ids = Spree::PageEvent.of_registered_users
                                    .where(actor_id: user_ids, actor_type: Spree.user_class.to_s, target_type: 'Spree::Product', activity: 'view')
                                    .where('created_at >= :scheduled_time', scheduled_time: scheduled_at)
                                    .distinct
                                    .pluck(:actor_id)

        Spree.user_class.where(id: actor_ids).pluck(:email)
      end

      def user_ids
        contacts.pluck(:user_id)
      end

      def generate_reports
        report_stats = {}
        list.class::AVAILABLE_REPORTS.each do |report|
          emails = send report
          count = emails.count
          report_stats[report.to_s.remove('_by')] = { 'emails' => emails, 'count' => count }
        end
        report_stats['emails_sent'] = contacts.count
        update(stats: JSON.parse(stats).merge(report_stats).to_json)
      end
    end
  end
end

app/models/spree/marketing/campaign.rb
module Spree
  module Marketing
    class Campaign < Spree::Base
      # Constants
      DEFAULT_SEND_TIME_GAP = 1.day
      STATS_COUNT_KEYS = %i[emails_sent emails_bounced emails_opened emails_delivered].freeze

      include Spree::Marketing::CalculateReports

      # Configurations
      self.table_name = 'spree_marketing_campaigns'

      # Validations
      validates :uid, :name, :stats, :list, :scheduled_at, :mailchimp_type, presence: true
      validates :uid, uniqueness: { case_sensitive: false }, allow_blank: true

      # Associations
      belongs_to :list, -> { with_deleted }, class_name: 'Spree::Marketing::List'
      has_many :recipients, class_name: 'Spree::Marketing::Recipient', dependent: :restrict_with_error
      has_many :contacts, through: :recipients

      # Callbacks
      after_create :enqueue_update

      def self.generate(campaigns_data)
        campaigns_data.collect do |data|
          list = Spree::Marketing::List.with_deleted.find_by(uid: data['recipients']['list_id'])
          new(uid: data['id'],
              mailchimp_type: data['type'],
              name: data['settings']['title'],
              list: list,
              scheduled_at: data['send_time'])
        end
      end

      def self.sync(since_send_time = nil)
        CampaignSyncJob.perform_later(since_send_time || DEFAULT_SEND_TIME_GAP.ago.to_s)
      end

      def populate(recipients_data)
        if save
          recipients_data.each do |recipient_data|
            contact = Spree::Marketing::Contact.find_by(uid: recipient_data['email_id'])
            recipient = Spree::Marketing::Recipient.create(contact: contact,
                                                           campaign: self,
                                                           email_opened_at: recipient_data['last_open'])
          end
          # ignoring case when not saved
        end
      end

      def update_stats(report_data)
        emails_bounced_count = report_data['bounces'].values.reduce(&:+)
        updated_stat_counts = {
          emails_sent: report_data['emails_sent'],
          emails_bounced: emails_bounced_count,
          emails_opened: report_data['opens']['unique_opens'],
          emails_delivered: report_data['emails_sent'] - emails_bounced_count
        }.to_json
        if !stats || (stats && stat_counts != updated_stat_counts)
          self.stats = updated_stat_counts
          save
        end
      end

      def stat_counts
        JSON.parse(stats).symbolize_keys.slice(*STATS_COUNT_KEYS)
      end

      private
        def enqueue_update
          4.times do |schedule_count|
            wait_until_time = scheduled_at + ((schedule_count + 1) * 6).hours
            if wait_until_time > Time.current
              enqueue_stats_update_job(wait_until_time)
              enqueue_reports_generation_job(wait_until_time)
            end
          end
        end

        def enqueue_stats_update_job(wait_until_time)
          CampaignModificationJob.set(wait_until: wait_until_time).perform_later id
        end

        def enqueue_reports_generation_job(wait_until_time)
          ReportsGenerationJob.set(wait_until: wait_until_time).perform_later id
        end
    end
  end
end

app/models/spree/marketing/contact.rb
module Spree
  module Marketing
    class Contact < Spree::Base
      # Configurations
      self.table_name = 'spree_marketing_contacts'

      # Associations
      has_many :contacts_lists, class_name: 'Spree::Marketing::ContactsList', dependent: :restrict_with_error
      has_many :lists, through: :contacts_lists
      has_many :recipients, class_name: 'Spree::Marketing::Recipient', dependent: :restrict_with_error
      has_many :campaigns, through: :recipients
      belongs_to :user, class_name: Spree.user_class.to_s

      # Validations
      validates :uid, :email, :mailchimp_id, presence: true
      validates :uid, :email, uniqueness: { case_sensitive: false }, allow_blank: true

      # Scopes
      scope :active, -> { where(active: true) }

      def self.load(data)
        find_or_create_by(email: data['email_address'],
                          uid: data['id'],
                          mailchimp_id: data['unique_email_id'],
                          user_id: data['user_id'])
      end
    end
  end
end

app/models/spree/marketing/contacts_list.rb
module Spree
  module Marketing
    class ContactsList < Spree::Base
      # Configurations
      self.table_name = 'spree_marketing_contacts_lists'

      # Associations
      belongs_to :contact, class_name: 'Spree::Marketing::Contact'
      belongs_to :list, class_name: 'Spree::Marketing::List'

      # scopes
      scope :with_contact_ids, ->(contact_ids) { where(contact_id: contact_ids) }

      # Validations
      validates :contact, :list, presence: true
    end
  end
end

app/models/spree/marketing/list.rb
module Spree
  module Marketing
    class List < Spree::Base
      acts_as_paranoid

      # Constants
      TIME_FRAME = 1.week
      NAME_TEXT = 'List'
      AVAILABLE_REPORTS = %i[cart_additions_by log_ins_by product_views_by purchases_by].freeze

      # Configurations
      self.table_name = 'spree_marketing_lists'

      # Associations
      has_many :contacts_lists, class_name: 'Spree::Marketing::ContactsList', dependent: :destroy
      has_many :contacts, through: :contacts_lists
      has_many :campaigns, class_name: 'Spree::Marketing::Campaign', dependent: :restrict_with_error
      # entity is the associated record for which the list is defined(e.g. Spree::Product for 'Favourable Products')
      belongs_to :entity, polymorphic: true

      # Validations
      validates :uid, :name, presence: true
      validates :uid, uniqueness: { case_sensitive: false }, allow_blank: true

      # Scopes
      scope :active, -> { where(active: true) }

      def user_ids
        raise ::NotImplementedError, 'You must implement user_ids method for this smart list.'
      end

      def generate
        ListGenerationJob.perform_later display_name, users_data, self.class.name, entity_data
      end

      def update_list
        _users_data = users_data
        _old_users_data = old_users_data
        emails = _users_data.keys
        old_emails = _old_users_data.keys
        subscribable_users_data = users_data.slice(*(emails - old_emails))
        ListModificationJob.perform_later id, subscribable_users_data, removable_contact_uids(old_emails - emails)
      end

      def self.generator
        list = find_by(name: self::NAME_TEXT)
        list ? list.update_list : new(name: self::NAME_TEXT).generate
      end

      def self.generate_all
        subclasses.each(&:generator)
      end

      def populate(contacts_data, users_data)
        contacts_data.each do |contact_data|
          contact = Spree::Marketing::Contact.load(contact_data.slice('email_address', 'id', 'unique_email_id')
                                                               .merge('user_id' => users_data[contact_data['email_address']]))
          contacts << contact
        end
      end

      def presenter
        Spree::Marketing::ListPresenter.new self
      end

      def display_name
        self.class::NAME_TEXT
      end

      def entity_name
        nil
      end

      def self.computed_time
        Time.current - self::TIME_FRAME
      end
      private_class_method :computed_time

      protected

        def all_users(emails)
          registered_users = Spree.user_class.where(email: emails)

          user_emails = registered_users.pluck(:email)
          unregistered_emails = emails - user_emails

          unregistered_users = unregistered_emails.map{|email| Spree.user_class.new(email: email) }

          registered_users.to_a + unregistered_users
        end

      private
        def computed_time
          self.class.send :computed_time
        end

        def users
          Spree.user_class.where(id: user_ids)
        end

        def users_data
          users.pluck(:email, :id).to_h
        end

        def removable_contact_uids(removable_emails)
          Spree::Marketing::Contact.where(email: removable_emails).pluck(:uid)
        end

        def old_users_data
          contacts.pluck(:email, :user_id).to_h
        end

        def entity_data
          { entity_id: entity_id, entity_type: entity_type, searched_keyword: searched_keyword }
        end
    end
  end
end

app/models/spree/marketing/list/abandoned_cart.rb
module Spree
  module Marketing
    class List
      class AbandonedCart < Spree::Marketing::List
        # Constants
        NAME_TEXT = 'Abandoned Cart'
        AVAILABLE_REPORTS = [:purchases_by].freeze

        private

          def users
            order_emails = Spree::Order.incomplete.where.not(item_count: 0).distinct.pluck(:email).compact.uniq

            all_users(order_emails)
          end

      end
    end
  end
end

app/models/spree/marketing/list/favourable_products.rb
module Spree
  module Marketing
    class List
      class FavourableProducts < Spree::Marketing::List
        include Spree::Marketing::ActsAsMultiList

        # Constants
        NAME_TEXT = 'Most Selling Products'
        ENTITY_KEY = 'entity_id'
        ENTITY_TYPE = 'Spree::Product'
        TIME_FRAME = 1.month
        FAVOURABLE_PRODUCT_COUNT = 10
        AVAILABLE_REPORTS = %i[cart_additions_by purchases_by product_views_by].freeze

        def user_ids
          # FIXME: There might be a case where a guest user have placed an order
          # And we also have his email but we are leaving those emails for now.
          Spree::Order.joins(line_items: { variant: :product })
                      .of_registered_users
                      .where('spree_orders.completed_at >= :time_frame', time_frame: computed_time)
                      .where('spree_products.id = ?', entity_id)
                      .group(:user_id)
                      .pluck(:user_id)
        end

        def self.data
          Spree::Order.joins(line_items: { variant: :product })
                      .where('spree_orders.completed_at >= :time_frame', time_frame: computed_time)
                      .group('spree_products.id')
                      .order(Arel.sql("COUNT(spree_orders.id) DESC"))
                      .limit(FAVOURABLE_PRODUCT_COUNT)
                      .pluck('spree_products.id')
        end
        private_class_method :data
      end
    end
  end
end

app/models/spree/marketing/list/least_active_users.rb
module Spree
  module Marketing
    class List
      class LeastActiveUsers < Spree::Marketing::List
        # Constants
        NAME_TEXT = 'Least Active Users'
        MAXIMUM_PAGE_EVENT_COUNT = 5
        AVAILABLE_REPORTS = %i[log_ins_by purchases_by product_views_by cart_additions_by].freeze

        def user_ids
          Spree::PageEvent.group(:actor_id)
                          .having('COUNT(spree_page_events.id) < :maximum_count', maximum_count: MAXIMUM_PAGE_EVENT_COUNT)
                          .of_registered_users
                          .where('created_at >= :time_frame', time_frame: computed_time)
                          .where(actor_type: Spree.user_class.to_s)
                          .pluck(:actor_id)
        end
      end
    end
  end
end

app/models/spree/marketing/list/most_active_users.rb
module Spree
  module Marketing
    class List
      class MostActiveUsers < Spree::Marketing::List
        # Constants
        NAME_TEXT = 'Most Active Users'
        MINIMUM_PAGE_EVENT_COUNT = 5
        AVAILABLE_REPORTS = %i[cart_additions_by purchases_by product_views_by].freeze

        def user_ids
          Spree::PageEvent.group(:actor_id)
                          .having('COUNT(spree_page_events.id) > ?', MINIMUM_PAGE_EVENT_COUNT)
                          .where('created_at >= :time_frame', time_frame: computed_time)
                          .of_registered_users
                          .where(actor_type: Spree.user_class.to_s)
                          .pluck(:actor_id)
        end
      end
    end
  end
end

app/controllers/spree/admin/marketing/campaigns_controller.rb
module Spree
  module Admin
    module Marketing
      class CampaignsController < Spree::Admin::ResourceController
        before_action :load_reports, only: %i[show display_recipient_emails]

        def sync
          Spree::Marketing::Campaign.sync
          render json: {
            flash: t('.success')
          }, status: 200
        end

        def display_recipient_emails
          @report_name = params[:report_key]
          @recipients = @marketing_campaign.recipients.with_emails(@reports[params[:report_key]]['emails']).page(params[:page]).per(20)
          @users_activity_hash = @recipients.activity_data params[:report_key], @marketing_campaign.scheduled_at
        end

        private
          def collection
            @campaigns = Spree::Marketing::Campaign.order(scheduled_at: :desc)
          end

          def load_reports
            @stats = JSON.parse @marketing_campaign.stats
            @reports = @stats.slice(*Spree::Marketing::Campaign::REPORT_TITLE_KEYS)
          end
      end
    end
  end
end

app/controllers/spree/admin/marketing/lists_controller.rb
module Spree
  module Admin
    module Marketing
      class ListsController < Spree::Admin::ResourceController
        before_action :load_contacts, only: :show

        private
          def collection
            Spree::Marketing::List.subclasses
                                  .map { |sub_class| sub_class.order(updated_at: :desc).all }
          end

          def load_contacts
            @contacts = @marketing_list.contacts.order(updated_at: :desc)
          end
      end
    end
  end
end

app/views/spree/admin/marketing/campaigns/display_recipient_emails.html.erb
<% content_for :page_title do %>
  <%= @marketing_campaign.name.titleize %> - <%= @report_name.titleize %> Report
  <p style="font-size: 15px;">
    Sent To: <%= @marketing_campaign.list.name %>
    <span class="icon icon-question-sign" data-toggle="tooltip" title="<%= @marketing_campaign.list.presenter.description %>"></span>
  </p>
  <p style="font-size: 15px;">Sent At: <%= @marketing_campaign.scheduled_at.to_formatted_s(:short) %></p>
<% end %>
<h3>Users</h3>
<hr />
<% if @recipients.present? %>
  <table class="table">
    <thead>
      <th><%= Spree.t(:email) %></th>
      <th><%= Spree.t(:email_opened_at) %></th>
      <th><%= Spree.t(:first_activity_at) %></th>
    </thead>
    <tbody>
      <% @recipients.each do |recipient| %>
        <tr>
          <td><%= recipient_email_or_link(recipient) %></td>
          <td><%= recipient.email_opened_at.to_formatted_s(:long) %></td>
          <td><%= @users_activity_hash[recipient.contact_email].to_formatted_s(:long) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <div class="alert alert-info no-objects-found">
    <%= Spree.t(:no_resource_found, resource: "Recipients") %>
  </div>
<% end %>

<%= paginate @recipients %>

app/views/spree/admin/marketing/campaigns/index.html.erb
<% content_for :page_title do %>
  <%= "Campaigns" %>
<% end %>

<% content_for :page_actions do %>
  <%= button_link_to Spree.t(:sync), admin_marketing_campaigns_sync_path, data: { remote: true, method: :post, type: 'JSON' }, class: 'btn-success campaign_sync', icon: 'refresh' %>
<% end %>


<% if @campaigns.present? %>
  <table class="table">
    <thead>
      <th class="col-md-3"><%= Spree::Marketing::List.human_attribute_name :name %></th>
      <th class="col-md-2"><%= Spree::Marketing::List.human_attribute_name :uid %></th>
      <th class="col-md-5 text-center"><%= Spree.t(:list_name) %></th>
      <th class="col-md-2"><%= Spree.t(:sent_at) %></th>
    </thead>
    <tbody>
      <% @campaigns.each do |campaign| %>
        <tr>
          <td class="col-md-3"><%= link_to campaign.name, admin_marketing_campaign_path(campaign) %></td>
          <td class="col-md-2"><%= campaign.uid %></td>
          <td class="col-md-5 text-center"><%= campaign.list.name %></td>
          <td class="col-md-3"><%= campaign.scheduled_at.to_formatted_s(:short) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <div class="alert alert-info no-objects-found">
    <%= Spree.t(:no_resource_found, resource: "Campaigns") %>
  </div>
<% end %>

<%= javascript_include_tag 'spree/backend/campaign_sync_flash_handler' %>

app/views/spree/admin/marketing/campaigns/show.html.erb
<script src="https://code.highcharts.com/highcharts.js"></script>
<script src="https://code.highcharts.com/modules/exporting.js"></script>
<%= javascript_include_tag 'spree/backend/campaign_data_report' %>
<%= stylesheet_link_tag 'spree/backend/campaign_report' %>

<% content_for :page_title do %>
  <%= @marketing_campaign.name.titleize %>
  <p style="font-size: 15px;">
    Sent To: <%= @marketing_campaign.list.name %>
    <span class="icon icon-question-sign" data-toggle="tooltip" title="<%= @marketing_campaign.list.presenter.description %>"></span>
  </p>
  <p style="font-size: 15px">
    Total Recipients: <%= @stats['emails_sent'] %>
  </p>
  <p style="font-size: 15px;">Sent At: <%= @marketing_campaign.scheduled_at.to_formatted_s(:short) %></p>
<% end %>


<% unless @stats['emails_sent'] == 0  %>
  <br />
  <div id="report_pie_chart" class="pie-chart-report"></div>
  <div class="pie-chart-data">
    <ul id="campaign_email_reports" class="campaign-email-reports">
      <li><div class="box delivered"></div>Delivered: <%= @stats['emails_delivered'] %></li>
      <li><div class="box bounced"></div>Bounced: <%= @stats['emails_bounced'] %></li>
      <li><div class="box opened"></div>Opened: <%= @stats['emails_opened'] %></li>
      <li><div class="box unopened"></div>Unopened: <%= @stats['emails_delivered'] - @stats['emails_opened'] %></li>
    </ul>
  </div>
  <div class="clear-fix"></div>
  <hr />

  <%= javascript_tag do %>
    var innerData = ([{ 'name': 'Delivered', 'y': <%= @stats['emails_delivered'] %>, 'color': '#105A9C' },
      { 'name': '', 'y': <%= @stats['emails_bounced'] %>, 'color': '#930F1C' }]);
    var outerData = ([{ 'name': 'Opened', 'y': <%= @stats['emails_opened'] %>, 'color': '#829909' },
      { 'name': 'Unopened', 'y': (<%= @stats['emails_delivered'] - @stats['emails_opened'] %>), 'color': '#ED7D05' },
      { 'name': 'Bounced', 'y': <%= @stats['emails_bounced'] %>, 'color': '#930F1C' }]);

    $(function (){
      var campaignDataReport = new CampaignDataReport($("#report_pie_chart"), innerData, outerData);
      campaignDataReport.init();
    });
  <% end %>
<% end %>

<h3>Reports</h3>
<br/ >
<% if @reports.present? && @stats['emails_sent'] != 0 %>
  <table class="table">
    <thead>
      <th class="col-md-4"><%= Spree.t(:name) %></th>
      <th class="col-md-4 text-center"><%= Spree.t(:occurences) %></th>
    </thead>
    <tbody>
      <% @reports.each do |report_name, report_data| %>
        <tr>
          <td class="col-md-4"><%= link_to report_name.titleize, display_recipient_emails_admin_marketing_campaign_path(report_key: report_name) %></td>
          <td class="col-md-4 text-center"><%= report_data["count"].to_s %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <div class="alert alert-info no-objects-found">
    <%= Spree.t(:no_reports_found) %>
  </div>
<% end %>